services:
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5674:5672
      - 15674:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq